### ISSUE TITLE
Dot not installed

### ISSUE THREAD

**Issue by martindurant** [conda-forge/python-graphviz-feedstock#15]
Installing with the linked [environment](https://github.com/martindurant/dask-tutorial-scipy-2018/blob/master/environment.yml), dask's visualize method (run from a jupyter-lab notebook)  produces
```
ExecutableNotFound: failed to execute ['dot', '-Tpng'], make sure the Graphviz executables are on your systems' PATH
```

**Comment by martindurant** [comment]
Actually, the executable `dot` **is** in the bin/ directory of the environment.

**Comment by martindurant** [comment]
Depending on whether I try from a terminal directly, where `dot` is definitely installed, getting
```
Warning: Could not load "/opt/conda/envs/dask-scipy/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/opt/conda/envs/dask-scipy/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/opt/conda/envs/dask-scipy/lib/graphviz/libgvplugin_pango.so.6" - file not found
Format: "png" not recognized. Use one of: bmp canon cmap cmapx cmapx_np dot eps fig gv ico imap imap_np ismap jpe jpeg jpg pdf pic plain plain-extpng pov ps ps2 svg svgz tif tiff tk vml vmlz xdot xdot1.2 xdot1.4
```

**Comment by martindurant** [comment]
( https://github.com/conda-forge/graphviz-feedstock/issues/18 ?)

**Comment by jakirkham** [comment]
Have you installed the [`yum` requirements]( https://github.com/conda-forge/graphviz-feedstock/blob/046c1d35d8c8f6042d253d74220a323c1c5b388b/recipe/yum_requirements.txt ) with your system package manager?

**Comment by martindurant** [comment]
I don't understand - the whole point of the conda install is not to have to do such things, else I would just install graphviz with yum too.

**Comment by jakirkham** [comment]
So I'm open to having this discussion, but think we need to shift forum to the [webpage repo]( https://github.com/conda-forge/conda-forge.github.io/ ). Otherwise it will be buried in a feedstock issue and hard to find/link to in the future. Could I ask you to open this issue?

**Comment by martindurant** [comment]
The issue is specific to installing graphviz, so this seems like exactly the right place to discuss it, or in the graphviz-feedstock repo. As you know, graphviz has proven a particularly annoying thorn to dask visualisation, and would love to have an in-one conda solution.

**Comment by jakirkham** [comment]
To be clear, I'm saying that a discussion about how to eliminate dependencies on system package managers (e.g. `yum`) is an org wide discussion and needs to be moved to the webpage repo for higher visibility and to actually coordinate a solution (as I agree one is needed). Certainly graphviz is one case, but it is not the only one.

**Comment by scopatz** [comment]
I agree that this could benefit from broader discussion

**Comment by jakirkham** [comment]
This case should be fixed now as PR ( https://github.com/conda-forge/graphviz-feedstock/pull/23 ) switched to using conda-forge's X11 packages, which negates the need for `yum` in the case of `graphviz`.
