### ISSUE TITLE
Conda version of 0.16 broken on windows

### ISSUE THREAD

**Issue by rwedge** [conda-forge/python-graphviz-feedstock#42]
Running this code:

```python-traceback
> import graphviz
> graphviz.Digraph().pipe()
...
graphviz.backend.ExecutableNotFound: failed to executed ['dot', '-Kdot.bat', '-Tpdf'],
make sure the Graphviz executables are on your systems' PATH
```

I believe this was caused by https://github.com/xflr6/graphviz/commit/422adc1fde7b8a1ecd383dd7f17e7b319bd610d4 changing the command from 

```python
cmd = [engine, '-T%s' % ':'.join(output_format)]
```

to this

```python
cmd = ['dot', '-K%s' % engine, '-T%s' % ':'.join(output_format)]
```

Since 'dot' is used directly instead of through `engine`, it doesn't get changed from 'dot' to 'dot.bat' and the command fails because dot can't be found

@xflr6 thoughts on how to fix this?

**Comment by xflr6** [comment]
Thanks @rwedge.

+1, looks like 28e281412affc5468d72ae65caff892fe6d78093 missed to update the `.patch` file that is used here:

https://github.com/conda-forge/python-graphviz-feedstock/blob/6311c81f256de360768dba06ed0789cc3d8c066a/recipe/windows-bat.patch#L7-L8

Caveat that I don't maintain this (conda) package/distribution: @scopatz or @jakirkham, can you take a look?

To clarify: The [vanilla-version  of `graphviz`](https://pypi.org/project/graphviz/#files) works on Windows (using the [vanilla-version of Graphviz](https://www.graphviz.org/download/)): IIRC, the conda-distribution of Graphviz includes `.bat`-wrappers for the layout commands to work around some library loading issue (not sure if that is still needed).

**Comment by rwedge** [comment]
Not sure if the wrappers are still necessary but I can try updating the patch file

**Comment by jakirkham** [comment]
Yeah the wrappers are still needed. Thanks for working on a patch.
