### ISSUE TITLE
Incorrect minimum Python version

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/python-graphviz-feedstock#58]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This package lists pythpn >=3 as a dependency.  However, since v0.20.2, python v3.8 has been required as a minimum version by the [upstream repo](https://github.com/xflr6/graphviz/blob/0.20.2/setup.py), and breaking code changes have been made which ensure this requirement.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by DManowitz** [comment]
I see that PR #56 should fix this, but it has not been merged yet.

**Comment by jameslamb** [comment]
This was fixed by #56. I don't have permission to close it, maybe @DManowitz you could please?
